export const ORDER_STATUS_PENDING = "PENDING";
export const ORDER_STATUS_PROCESSING = "PROCESSING";
export const ORDER_STATUS_CONFIRMED = "CONFIRMED";
export const ORDER_STATUS_COMPLETED = "COMPLETED";
export const ORDER_STATUS_SHIPPED = "SHIPPED";
export const ORDER_STATUS_CANCELLED = "CANCELLED";
export const ORDER_STATUS_DELIVERED = "DELIVERED";
export const ORDER_STATUS_RETURNED = "RETURNED";
